export const CHANGE_SEARCH_FIELD = 'CHANGE_SEARCH_FIELD';
export const FETCH_ROBOT_PENDING = 'FETCH_ROBOT_PENDING'
export const FETCH_ROBOT_SUCCESS = 'FETCH_ROBOT_SUCCESS'
export const FETCH_ROBOT_FAILED = 'FETCH_ROBOT_FAILED'
